### ISSUE TITLE
chrome的那个css能否在多个标题栏中间添加分割线？

### ISSUE THREAD

**Issue by cc19264997** [tyuhao/TYHfox#1]
感谢！

**Comment by tyuhao** [comment]
https://firefoxcss-store.github.io/
去这个网站看看有没有分割线的，然后把需要的代码放进去就好了

**Comment by cc19264997** [comment]
感谢，虽然全英文，还看不懂代码，还是感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tyuhao/TYHfox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tyuhao/TYHfox] chrome的那个css能否在多个标题栏中间添加分割线？ (Issue #1)





 
https://firefoxcss-store.github.io/
 去这个网站看看有没有分割线的，然后把需要的代码放进去就好了
